version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - curl --silent --location https://rpm.nodesource.com/setup_12.x | bash -
      - yum -y install nodejs
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  name: build-package
